# -*- coding: utf-8 -*-
"""Course_Project26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mw0y0SEfvOUJr3XjgOl0Q74Y08OKDbIB
"""

# [CELL 1] Install + environment check

!pip -q install networkx==3.3 pandas numpy matplotlib tqdm

import sys, platform
print("Python:", sys.version.split()[0])
print("Platform:", platform.platform())

# [CELL 2] Imports + global seed helper

import math
import random
from dataclasses import dataclass, asdict
from typing import Dict, Any, List, Tuple, Optional

import numpy as np
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
from tqdm.auto import tqdm

from scipy.stats import kruskal, mannwhitneyu, chi2_contingency
from statsmodels.stats.multitest import multipletests
from itertools import combinations

def set_global_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)

print("Imports OK ✅")

# [CELL 3] Graph generators (ER / WS / BA / CMP) and target average degree matching

def make_er(n: int, k_target: float, seed: int) -> nx.Graph:
    # For ER: expected avg degree ≈ p*(n-1) => p ≈ k/(n-1)
    p = float(k_target) / max(n - 1, 1)
    p = min(max(p, 0.0), 1.0)
    G = nx.erdos_renyi_graph(n=n, p=p, seed=seed)
    return G

def make_ws(n: int, k_target: int, beta: float, seed: int) -> nx.Graph:
    # For WS: k must be even and satisfy 0 < k < n
    if n < 3:
        raise ValueError("Watts-Strogatz graph requires n >= 3")

    k = int(round(k_target))

    # k must be less than n
    k = min(k, n - 1)

    # k must be even
    if k % 2 == 1:
        k -= 1

    # keep >= 2 neighbors if possible
    k = max(2, k)

    # if n is very small and k == n, reduce again
    if k >= n:
        k = n - 1
        if k % 2 == 1:
            k -= 1

    if k < 2:
        raise ValueError(f"Invalid WS k={k} for n={n}")

    return nx.watts_strogatz_graph(n=n, k=k, p=beta, seed=seed)

def make_ba(n: int, k_target: float, seed: int) -> nx.Graph:
    # For BA: avg degree ≈ 2m  => m ≈ k/2
    m = int(max(1, round(k_target / 2)))
    m = min(m, n - 1)
    G = nx.barabasi_albert_graph(n=n, m=m, seed=seed)
    return G
def expected_avg_degree_block_model(n: int, sizes: List[int], P: np.ndarray) -> float:
    """
    Expected average degree for an undirected stochastic block model.
    """
    expected_edges = 0.0
    B = len(sizes)

    for a in range(B):
        for b in range(a, B):
            if a == b:
                possible_edges = sizes[a] * (sizes[a] - 1) / 2
            else:
                possible_edges = sizes[a] * sizes[b]

            expected_edges += possible_edges * P[a, b]

    return 2.0 * expected_edges / n


def calibrate_block_probabilities(
    n: int,
    sizes: List[int],
    base_affinity: np.ndarray,
    k_target: float,
    p_max: float = 0.95,
    n_iter: int = 60
) -> np.ndarray:
    """
    Scales a base affinity matrix so that expected average degree
    is approximately equal to k_target.
    """
    base_affinity = np.asarray(base_affinity, dtype=float)

    lo, hi = 0.0, 1.0

    # Increase upper bound until expected degree is high enough
    for _ in range(50):
        P_hi = np.minimum(hi * base_affinity, p_max)
        k_hi = expected_avg_degree_block_model(n, sizes, P_hi)
        if k_hi >= k_target:
            break
        hi *= 2.0

    # Binary search for scale
    for _ in range(n_iter):
        mid = (lo + hi) / 2.0
        P_mid = np.minimum(mid * base_affinity, p_max)
        k_mid = expected_avg_degree_block_model(n, sizes, P_mid)

        if k_mid < k_target:
            lo = mid
        else:
            hi = mid

    return np.minimum(hi * base_affinity, p_max)


def ensure_connected_by_bridges(G: nx.Graph, seed: int) -> nx.Graph:
    """
    Keeps all nodes and connects disconnected components by adding bridges.
    This preserves N across all topologies.
    """
    if nx.is_connected(G):
        return G

    rng = np.random.default_rng(seed)
    components = [list(c) for c in nx.connected_components(G)]
    components = sorted(components, key=len, reverse=True)

    main = components[0]

    for comp in components[1:]:
        u = int(rng.choice(main))
        v = int(rng.choice(comp))
        G.add_edge(u, v)
        main.extend(comp)

    return G

def make_core_middle_periphery(
    n: int,
    k_target: float,
    seed: int,
    core_frac: float = 0.10,
    middle_frac: float = 0.25
) -> nx.Graph:
    """
    Stylized core-middle-periphery topology.

    For N=300 by default:
    - core ≈ 30 nodes
    - middle ≈ 75 nodes
    - periphery ≈ 195 nodes
    """
    rng = np.random.default_rng(seed)

    n_core = int(round(core_frac * n))
    n_middle = int(round(middle_frac * n))
    n_periphery = n - n_core - n_middle

    n_core = max(2, n_core)
    n_middle = max(2, n_middle)
    n_periphery = max(2, n_periphery)

    total = n_core + n_middle + n_periphery
    if total != n:
        n_periphery += n - total

    sizes = [n_core, n_middle, n_periphery]

    base_affinity = np.array([
    [1.00, 0.50, 0.05],
    [0.50, 0.22, 0.12],
    [0.05, 0.12, 0.01],
])

    P = calibrate_block_probabilities(
        n=n,
        sizes=sizes,
        base_affinity=base_affinity,
        k_target=k_target,
        p_max=0.95
    )

    G = nx.stochastic_block_model(
        sizes=sizes,
        p=P,
        seed=seed,
        directed=False,
        selfloops=False
    )

    layer_names = ["core", "middle", "periphery"]
    node_layer = {}
    start = 0

    for layer_name, size in zip(layer_names, sizes):
        for node in range(start, start + size):
            node_layer[node] = layer_name
        start += size

    nx.set_node_attributes(G, node_layer, "layer")

    G = ensure_connected_by_bridges(G, seed=seed)

    G.graph["block_sizes"] = {
        "core": n_core,
        "middle": n_middle,
        "periphery": n_periphery
    }
    G.graph["block_probabilities"] = P

    return G

def ensure_largest_component(G: nx.Graph) -> nx.Graph:
    if nx.is_connected(G):
        return G
    comp = max(nx.connected_components(G), key=len)
    return G.subgraph(comp).copy()

def graph_summary(G: nx.Graph) -> Dict[str, Any]:
    n = G.number_of_nodes()
    m = G.number_of_edges()
    degs = np.array([d for _, d in G.degree()])
    avg_deg = float(degs.mean()) if n > 0 else 0.0
    density = nx.density(G) if n > 1 else 0.0
    clustering = nx.average_clustering(G) if n > 0 else 0.0

    # Avg shortest path length only for connected graphs (or use largest component)
    if n > 1 and nx.is_connected(G):
        aspl = nx.average_shortest_path_length(G)
    else:
        aspl = np.nan

    return {
        "n": n,
        "m": m,
        "avg_deg": avg_deg,
        "density": density,
        "clustering": clustering,
        "avg_shortest_path_len": aspl,
        "deg_min": int(degs.min()) if n > 0 else 0,
        "deg_max": int(degs.max()) if n > 0 else 0,
        "deg_p90": float(np.percentile(degs, 90)) if n > 0 else 0.0,
    }

def build_topologies(
    n: int,
    k_target: float,
    ws_beta: float,
    seed: int,
    ensure_connected: bool = True
) -> Dict[str, nx.Graph]:
    G_er = make_er(n, k_target, seed=seed)
    G_ws = make_ws(n, k_target=int(round(k_target)), beta=ws_beta, seed=seed)
    G_ba = make_ba(n, k_target, seed=seed)
    G_cmp = make_core_middle_periphery(n=n, k_target=k_target, seed=seed)

    if ensure_connected:
        G_er = ensure_connected_by_bridges(G_er, seed=seed + 1)
        G_ws = ensure_connected_by_bridges(G_ws, seed=seed + 2)
        G_ba = ensure_connected_by_bridges(G_ba, seed=seed + 3)
        G_cmp = ensure_connected_by_bridges(G_cmp, seed=seed + 4)

    return {
        "ER": G_er,
        "WS": G_ws,
        "BA": G_ba,
        "CMP": G_cmp
    }

# [CELL 4] Quick visualization of graphs (optional)

def plot_graph(G: nx.Graph, title: str, seed: int = 0, max_nodes: int = 300):
    H = G
    if H.number_of_nodes() > max_nodes:
        nodes = list(H.nodes())
        rng = np.random.default_rng(seed)
        keep = set(rng.choice(nodes, size=max_nodes, replace=False))
        H = H.subgraph(keep).copy()

    pos = nx.spring_layout(H, seed=seed)
    plt.figure(figsize=(6, 5))
    nx.draw_networkx_nodes(H, pos, node_size=10, alpha=0.8)
    nx.draw_networkx_edges(H, pos, width=0.3, alpha=0.4)
    plt.title(title)
    plt.axis("off")
    plt.show()

# Demo
set_global_seed(42)

tops = build_topologies(
    n=300,
    k_target=10,
    ws_beta=0.15,
    seed=42,
    ensure_connected=True
)

for name, G in tops.items():
    print(name, graph_summary(G))
    plot_graph(
        G,
        f"{name} (n={G.number_of_nodes()}, avg_deg≈{graph_summary(G)['avg_deg']:.2f})",
        seed=42
    )

#Double-checking if CMP is built correctly
def cmp_layer_summary(G: nx.Graph) -> pd.DataFrame:
    rows = []

    for layer in ["core", "middle", "periphery"]:
        nodes = [u for u, data in G.nodes(data=True) if data.get("layer") == layer]
        degs = np.array([G.degree(u) for u in nodes], dtype=float)

        rows.append({
            "layer": layer,
            "n_nodes": len(nodes),
            "mean_degree": float(degs.mean()) if len(degs) > 0 else np.nan,
            "median_degree": float(np.median(degs)) if len(degs) > 0 else np.nan,
            "max_degree": float(degs.max()) if len(degs) > 0 else np.nan,
            "min_degree": float(degs.min()) if len(degs) > 0 else np.nan,
        })

    return pd.DataFrame(rows)

cmp_summary = cmp_layer_summary(tops["CMP"])
display(cmp_summary)

# [CELL 5] ABM config + helper functions


@dataclass
class SimConfig:
    # Network / simulation
    # T - the maximum simulation horizon
    # If stop_when_stable=True, the simulation stops earlier when aggregate dynamics become stable.
    T: int = 100
    stop_when_stable: bool = True
    stability_window: int = 5
    stability_eps: float = 1e-4
    min_steps: int = 10

    shock_fraction: float = 0.05       # fraction of nodes shocked at t=0
    shock_mode: str = "random"         # "random" or "targeted"
    shock_strength: float = 0.35       # stress added at t=0
    initial_shock_state: str = "stress"  # "stress", "distress", or "default"

    # Stress update core
    r: float = 0.08                    # recovery rate (0..1)
    beta: float = 0.25                 # transmission strength
    normalize_incoming: bool = True    # divide incoming stress by node degree
    clip_min: float = 0.0
    clip_max: float = 1.0

    # Thresholds
    theta_distress_mean: float = 0.55
    theta_distress_std: float = 0.08
    theta_default_mean: float = 0.85
    theta_default_std: float = 0.05

    # Systemic-event thresholds for output metrics
    systemic_default_threshold: float = 0.30   # systemic event if final_default >= 30%
    systemic_cascade_threshold: float = 0.50   # systemic event if cascade_size >= 50%

    # Scenario toggles
    use_liquidity_spiral: bool = False
    use_leverage_feedback: bool = False
    use_herding: bool = False

    # Liquidity spiral parameters
    liquidity_t_start: int = 5
    liquidity_t_end: int = 18
    liquidity_beta_mult: float = 1.35  # beta increases during liquidity stress
    liquidity_r_mult: float = 0.75     # recovery becomes weaker during liquidity stress

    # Leverage feedback parameters
    tau_mean: float = 0.65
    tau_std: float = 0.10
    leverage_lambda: float = 0.8       # outgoing stress multiplier if s_i > tau_i

    # Herding parameters
    phi_mean: float = 0.35             # threshold of distressed/defaulted-neighbor share
    phi_std: float = 0.08
    herding_h: float = 0.40            # additive stress: h*(q_i - phi_i)+

    # Edge weights
    directed_weights: bool = False     # if True: random directed weights per edge
    weight_scale: float = 1.0


def _draw_normal_clip(
    rng: np.random.Generator,
    mean: float,
    std: float,
    size: int,
    lo: float = 0.0,
    hi: float = 1.0
):
    x = rng.normal(mean, std, size=size)
    return np.clip(x, lo, hi)


def pick_shocked_nodes(G: nx.Graph, frac: float, mode: str, seed: int) -> List[int]:
    rng = np.random.default_rng(seed)
    nodes = list(G.nodes())
    k = int(max(1, round(frac * len(nodes))))

    if mode == "random":
        return list(rng.choice(nodes, size=k, replace=False))

    if mode == "targeted":
        # Target structurally central agents: highest-degree nodes.
        deg = dict(G.degree())
        nodes_sorted = sorted(nodes, key=lambda x: deg[x], reverse=True)
        return nodes_sorted[:k]

    raise ValueError(f"Unknown shock_mode={mode}")

# [CELL 6] Core simulation: stress propagation + scenarios + stabilization stopping

# 3 possible states: Ok, Distressed (recovery is still possible), Default
STATE_OK = 0
STATE_DISTRESSED = 1
STATE_DEFAULTED = 2


def simulate_once(G: nx.Graph, cfg: SimConfig, seed: int) -> Dict[str, Any]:
    """
    Stylized threshold-based ABM of systemic-risk propagation.

    Interpretation:
    - s_i(t): normalized stress level of agent i
    - DISTRESSED: stress exceeds individual distress threshold
    - DEFAULTED: stress exceeds individual default threshold
    - cascade_size: fraction of nodes that ever become DISTRESSED or DEFAULTED

    The simulation runs until either:
    1. aggregate dynamics stabilize, if cfg.stop_when_stable=True; or
    2. the maximum horizon cfg.T is reached.

    Therefore, cfg.T is a maximum simulation horizon, not as
    the actual crisis duration.
    """
    rng = np.random.default_rng(seed)

    nodes = list(G.nodes())
    idx = {u: i for i, u in enumerate(nodes)}
    n = len(nodes)

    # 1. Node-specific thresholds
    theta_d = _draw_normal_clip(
        rng,
        cfg.theta_distress_mean,
        cfg.theta_distress_std,
        n,
        lo=0.05,
        hi=0.99
    )

    theta_f = _draw_normal_clip(
        rng,
        cfg.theta_default_mean,
        cfg.theta_default_std,
        n,
        lo=0.10,
        hi=0.999
    )

    # Ensure default threshold is always above distress threshold
    theta_f = np.maximum(theta_f, theta_d + 0.05)
    theta_f = np.clip(theta_f, 0.10, 0.999)

    # Leverage thresholds tau_i
    tau = _draw_normal_clip(
        rng,
        cfg.tau_mean,
        cfg.tau_std,
        n,
        lo=0.05,
        hi=0.99
    )

    # Herding thresholds phi_i
    phi = _draw_normal_clip(
        rng,
        cfg.phi_mean,
        cfg.phi_std,
        n,
        lo=0.01,
        hi=0.99
    )

    # 2. Weighted neighbor lists
    if cfg.directed_weights:
        # in_neighbors[i] contains (j, w_ji), meaning stress flows from j to i
        in_neighbors = [[] for _ in range(n)]

        for u, v in G.edges():
            w_uv = float(rng.random() * cfg.weight_scale)
            w_vu = float(rng.random() * cfg.weight_scale)

            iu, iv = idx[u], idx[v]

            in_neighbors[iu].append((iv, w_vu))  # v -> u
            in_neighbors[iv].append((iu, w_uv))  # u -> v

    else:
        # Undirected stress-transmission weights
        in_neighbors = [[] for _ in range(n)]

        for u, v in G.edges():
            w_uv = float(rng.random() * cfg.weight_scale)

            iu, iv = idx[u], idx[v]

            in_neighbors[iu].append((iv, w_uv))
            in_neighbors[iv].append((iu, w_uv))

    # 3. Initial conditions

    s = np.zeros(n, dtype=float)
    state = np.zeros(n, dtype=int)  # all OK

    shocked = pick_shocked_nodes(
        G,
        frac=cfg.shock_fraction,
        mode=cfg.shock_mode,
        seed=seed
    )
    shocked_idx = [idx[u] for u in shocked]

    # Add initial stress
    s[shocked_idx] = np.clip(
        s[shocked_idx] + cfg.shock_strength,
        cfg.clip_min,
        cfg.clip_max
    )

    # Interpret initial shock
    if cfg.initial_shock_state == "distress":
        for ii in shocked_idx:
            # Push shocked agents into distress, but don't force immediate default
            s[ii] = max(s[ii], theta_d[ii])
            s[ii] = min(s[ii], theta_f[ii] - 1e-6)
            state[ii] = STATE_DISTRESSED

    elif cfg.initial_shock_state == "default":
        for ii in shocked_idx:
            s[ii] = max(s[ii], theta_f[ii])
            state[ii] = STATE_DEFAULTED

    elif cfg.initial_shock_state == "stress":
        state[s >= theta_d] = STATE_DISTRESSED
        state[s >= theta_f] = STATE_DEFAULTED

    else:
        raise ValueError(f"Unknown initial_shock_state={cfg.initial_shock_state}")

    # Track ever-affected nodes
    ever_affected = (state == STATE_DISTRESSED) | (state == STATE_DEFAULTED)
    ever_defaulted = (state == STATE_DEFAULTED)

    # 4. Time series containers

    ts_frac_distressed = []
    ts_frac_defaulted = []
    ts_frac_affected = []
    ts_avg_stress = []

    def record_state():
        ts_frac_distressed.append(float((state == STATE_DISTRESSED).mean()))
        ts_frac_defaulted.append(float((state == STATE_DEFAULTED).mean()))
        ts_frac_affected.append(
            float(((state == STATE_DISTRESSED) | (state == STATE_DEFAULTED)).mean())
        )
        ts_avg_stress.append(float(s.mean()))

    record_state()

    # 5. Main simulation loop

    stopped_early = False
    stop_time = cfg.T

    for t in range(cfg.T):
        beta_t = cfg.beta
        r_t = cfg.r

        # Liquidity stress: stronger transmission and weaker recovery
        if cfg.use_liquidity_spiral and (cfg.liquidity_t_start <= t <= cfg.liquidity_t_end):
            beta_t *= cfg.liquidity_beta_mult
            r_t *= cfg.liquidity_r_mult

        s_new = s.copy()

        distressed_mask = (state == STATE_DISTRESSED)
        defaulted_mask = (state == STATE_DEFAULTED)
        affected_mask = distressed_mask | defaulted_mask

        for i in range(n):
            if state[i] == STATE_DEFAULTED:
                # Default is absorbing
                s_new[i] = max(s_new[i], theta_f[i])
                continue

            incoming = 0.0

            for j, w_ji in in_neighbors[i]:
                # Stress contribution from neighbor j
                if defaulted_mask[j]:
                    g = 1.0
                elif distressed_mask[j]:
                    g = min(1.0, s[j] * 1.15)
                else:
                    g = s[j]

                # Leverage / margin feedback:
                # if neighbor j is above its leverage threshold, it transmits more stress
                if cfg.use_leverage_feedback and s[j] > tau[j]:
                    g *= (1.0 + cfg.leverage_lambda)

                incoming += w_ji * g

            deg_i = max(1, len(in_neighbors[i]))

            # Normalize incoming stress by degree in the baseline model
            if cfg.normalize_incoming:
                incoming /= deg_i

            # Core stress update
            s_new[i] = (1.0 - r_t) * s[i] + beta_t * incoming

            # Herding:
            # stress increases if the share of affected neighbors exceeds phi_i
            if cfg.use_herding:
                if deg_i > 0:
                    neighbor_ids = [j for j, _ in in_neighbors[i]]
                    q_i = float(affected_mask[neighbor_ids].mean())
                else:
                    q_i = 0.0

                if q_i >= phi[i]:
                    s_new[i] += cfg.herding_h * (q_i - phi[i])

            s_new[i] = float(np.clip(s_new[i], cfg.clip_min, cfg.clip_max))

        s = s_new

        # 6. State update

        new_state = state.copy()

        # Default is absorbing
        new_state[s >= theta_f] = STATE_DEFAULTED

        # Distress condition for non-defaulted nodes
        distressed_now = (s >= theta_d) & (new_state != STATE_DEFAULTED)

        # Recovery is allowed from DISTRESSED to OK, but not from DEFAULTED
        new_state[(~distressed_now) & (new_state != STATE_DEFAULTED)] = STATE_OK
        new_state[distressed_now] = STATE_DISTRESSED

        state = new_state

        # Update cascade tracking
        ever_affected |= (state == STATE_DISTRESSED) | (state == STATE_DEFAULTED)
        ever_defaulted |= (state == STATE_DEFAULTED)

        record_state()

      # 7. Optional early stopping

        min_stop_step = cfg.min_steps

        if cfg.use_liquidity_spiral:
            min_stop_step = max(
                min_stop_step,
                cfg.liquidity_t_end + cfg.stability_window + 1
            )

        if cfg.stop_when_stable and (t + 1) >= min_stop_step:
            window = int(cfg.stability_window)

            if len(ts_frac_affected) > window + 1:
                affected_recent = np.array(ts_frac_affected[-(window + 1):])
                default_recent = np.array(ts_frac_defaulted[-(window + 1):])
                stress_recent = np.array(ts_avg_stress[-(window + 1):])

                max_change_affected = float(np.max(np.abs(np.diff(affected_recent))))
                max_change_default = float(np.max(np.abs(np.diff(default_recent))))
                max_change_stress = float(np.max(np.abs(np.diff(stress_recent))))

                if (
                    max_change_affected <= cfg.stability_eps
                    and max_change_default <= cfg.stability_eps
                    and max_change_stress <= cfg.stability_eps
                ):
                    stopped_early = True
                    stop_time = t + 1
                    break

    # 8. Summary metrics

    cascade_size = float(ever_affected.mean())  # main cascade-size metric
    ever_defaulted_fraction = float(ever_defaulted.mean())

    final_affected = float(((state == STATE_DISTRESSED) | (state == STATE_DEFAULTED)).mean())
    final_default = float((state == STATE_DEFAULTED).mean())

    peak_default = float(np.max(ts_frac_defaulted))
    peak_distress = float(np.max(ts_frac_distressed))
    peak_affected = float(np.max(ts_frac_affected))

    default_arr = np.array(ts_frac_defaulted)
    affected_arr = np.array(ts_frac_affected)

    default_changes = np.where(np.abs(np.diff(default_arr)) > 1e-9)[0]
    affected_changes = np.where(np.abs(np.diff(affected_arr)) > 1e-9)[0]

    # Old duration-like metrics: last time when the fraction changed
    # These are kept for comparability, but they can be close to the horizon
    # when small changes continue until the end.
    # cascade_duration_default = int(default_changes[-1] + 1) if len(default_changes) > 0 else 0
    # cascade_duration_affected = int(affected_changes[-1] + 1) if len(affected_changes) > 0 else 0

    time_to_peak_default = int(np.argmax(default_arr))
    time_to_peak_affected = int(np.argmax(affected_arr))

    def first_time_reaching_fraction_of_peak(arr: np.ndarray, frac: float) -> int:
        peak = float(np.max(arr))
        if peak <= 1e-12:
            return 0

        target = frac * peak
        hits = np.where(arr >= target)[0]

        if len(hits) == 0:
            return 0

        return int(hits[0])

    time_to_50pct_peak_affected = first_time_reaching_fraction_of_peak(affected_arr, 0.50)
    time_to_90pct_peak_affected = first_time_reaching_fraction_of_peak(affected_arr, 0.90)

    time_to_50pct_peak_default = first_time_reaching_fraction_of_peak(default_arr, 0.50)
    time_to_90pct_peak_default = first_time_reaching_fraction_of_peak(default_arr, 0.90)

    active_cascade_duration_affected = max(
        0,
        time_to_90pct_peak_affected - time_to_50pct_peak_affected
    )

    active_cascade_duration_default = max(
        0,
        time_to_90pct_peak_default - time_to_50pct_peak_default
    )

    # Area under the curve: total burden of distress/default over time
    area_affected = float(np.trapezoid(affected_arr))
    area_default = float(np.trapezoid(default_arr))

    # Stabilization time:
    # first time after which changes remain smaller than eps until the end.
    def stabilization_time(arr: np.ndarray, eps: float = 1e-4) -> int:
        diffs = np.abs(np.diff(arr))

        if len(diffs) == 0:
            return 0

        for tt in range(len(diffs)):
            if np.all(diffs[tt:] <= eps):
                return int(tt)

        return int(len(arr) - 1)

    stabilization_time_affected = stabilization_time(affected_arr, eps=cfg.stability_eps)
    stabilization_time_default = stabilization_time(default_arr, eps=cfg.stability_eps)

    systemic_by_default = int(final_default >= cfg.systemic_default_threshold)
    systemic_by_cascade = int(cascade_size >= cfg.systemic_cascade_threshold)

    return {
        "seed": seed,
        "n": n,

        # Main outcomes
        "cascade_size": cascade_size,
        "final_default": final_default,
        "final_affected": final_affected,
        "ever_defaulted": ever_defaulted_fraction,

        # Peak outcomes
        "peak_default": peak_default,
        "peak_distress": peak_distress,
        "peak_affected": peak_affected,

        # Systemic-event flags
        "systemic_by_default": systemic_by_default,
        "systemic_by_cascade": systemic_by_cascade,

        # Timing outcomes
        # "cascade_duration_default": cascade_duration_default,
        # "cascade_duration_affected": cascade_duration_affected,
        "time_to_peak_default": time_to_peak_default,
        "time_to_peak_affected": time_to_peak_affected,

        "time_to_50pct_peak_affected": time_to_50pct_peak_affected,
        "time_to_90pct_peak_affected": time_to_90pct_peak_affected,
        "time_to_50pct_peak_default": time_to_50pct_peak_default,
        "time_to_90pct_peak_default": time_to_90pct_peak_default,

        "active_cascade_duration_affected": active_cascade_duration_affected,
        "active_cascade_duration_default": active_cascade_duration_default,

        "stabilization_time_affected": stabilization_time_affected,
        "stabilization_time_default": stabilization_time_default,

        "area_affected": area_affected,
        "area_default": area_default,

        # Stopping information
        "stopped_early": int(stopped_early),
        "stop_time": int(stop_time),
        "max_T": int(cfg.T),

        # Time series
        "ts_frac_distressed": ts_frac_distressed,
        "ts_frac_defaulted": ts_frac_defaulted,
        "ts_frac_affected": ts_frac_affected,
        "ts_avg_stress": ts_avg_stress,

        # Initial shock
        "shocked_count": len(shocked_idx),
    }

# [CELL 7] Experiment runner: multiple runs + metrics table


def run_experiment(
    G: nx.Graph,
    topology_name: str,
    cfg: SimConfig,
    n_runs: int,
    base_seed: int,
    graph_seed: Optional[int] = None,
    graph_id: Optional[int] = None,
) -> pd.DataFrame:
    """
    Runs multiple ABM simulations on one fixed graph.
    Stores both simulation outcomes and graph-level structural metrics.
    """
    rows = []

    # Graph-level structural metrics
    gsum = graph_summary(G)

    for r_i in tqdm(range(n_runs), desc=f"Runs {topology_name}", leave=False):
        seed = base_seed + r_i
        out = simulate_once(G, cfg, seed=seed)

        row = {
            # Identifiers
            "topology": topology_name,
            "run": r_i,
            "seed": seed,
            "graph_seed": graph_seed,
            "graph_id": graph_id,

            # Graph-level metrics
            "n": out["n"],
            "graph_m": gsum["m"],
            "graph_avg_deg": gsum["avg_deg"],
            "graph_density": gsum["density"],
            "graph_clustering": gsum["clustering"],
            "graph_avg_shortest_path_len": gsum["avg_shortest_path_len"],
            "graph_deg_min": gsum["deg_min"],
            "graph_deg_max": gsum["deg_max"],
            "graph_deg_p90": gsum["deg_p90"],

            # Main cascade outcomes
            "cascade_size": out["cascade_size"],
            "final_default": out["final_default"],
            "final_affected": out["final_affected"],
            "ever_defaulted": out["ever_defaulted"],

            # Peak outcomes
            "peak_default": out["peak_default"],
            "peak_distress": out["peak_distress"],
            "peak_affected": out["peak_affected"],

            # Systemic-event flags
            "systemic_by_default": out["systemic_by_default"],
            "systemic_by_cascade": out["systemic_by_cascade"],

            # Timing outcomes
            # "cascade_duration_default": out["cascade_duration_default"],
            # "cascade_duration_affected": out["cascade_duration_affected"],
            "time_to_peak_default": out["time_to_peak_default"],
            "time_to_peak_affected": out["time_to_peak_affected"],

            "time_to_50pct_peak_affected": out["time_to_50pct_peak_affected"],
            "time_to_90pct_peak_affected": out["time_to_90pct_peak_affected"],
            "time_to_50pct_peak_default": out["time_to_50pct_peak_default"],
            "time_to_90pct_peak_default": out["time_to_90pct_peak_default"],

            "active_cascade_duration_affected": out["active_cascade_duration_affected"],
            "active_cascade_duration_default": out["active_cascade_duration_default"],

            "stabilization_time_affected": out["stabilization_time_affected"],
            "stabilization_time_default": out["stabilization_time_default"],

            "area_affected": out["area_affected"],
            "area_default": out["area_default"],

            # Stopping information
            "stopped_early": out["stopped_early"],
            "stop_time": out["stop_time"],
            "max_T": out["max_T"],

            # Initial shock info
            "shocked_count": out["shocked_count"],
        }

        # Add config snapshot so CSV files are self-contained
        row.update({f"cfg_{k}": v for k, v in asdict(cfg).items()})

        rows.append(row)

    return pd.DataFrame(rows)


def run_all_topologies(
    topologies: Dict[str, nx.Graph],
    cfg: SimConfig,
    n_runs: int = 50,
    base_seed: int = 1000,
    graph_seed: Optional[int] = None,
    graph_id: Optional[int] = None,
) -> pd.DataFrame:
    """
    Runs simulations for all topology graphs in a dictionary.
    """
    dfs = []

    for name, G in topologies.items():
        df = run_experiment(
            G=G,
            topology_name=name,
            cfg=cfg,
            n_runs=n_runs,
            base_seed=base_seed,
            graph_seed=graph_seed,
            graph_id=graph_id,
        )
        dfs.append(df)

    return pd.concat(dfs, ignore_index=True)


def run_all_topologies_over_graphs(
    n: int,
    k_target: float,
    ws_beta: float,
    cfg: SimConfig,
    graph_seeds: List[int],
    n_runs_per_graph: int,
    base_seed: int,
) -> pd.DataFrame:
    """
    Runs simulations over multiple graph realizations for each topology.

    This accounts for:
    1. graph-generation randomness;
    2. shock/agent/threshold/weight randomness.
    """
    all_dfs = []

    for g_i, g_seed in enumerate(tqdm(graph_seeds, desc="Graph realizations")):
        topologies = build_topologies(
            n=n,
            k_target=k_target,
            ws_beta=ws_beta,
            seed=g_seed,
            ensure_connected=True
        )

        df = run_all_topologies(
            topologies=topologies,
            cfg=cfg,
            n_runs=n_runs_per_graph,
            base_seed=base_seed + g_i * 10000,
            graph_seed=g_seed,
            graph_id=g_i,
        )

        all_dfs.append(df)

    return pd.concat(all_dfs, ignore_index=True)

# [CELL 8] Baseline run (no scenarios) + save


set_global_seed(123)

# Baseline network setup
N = 300
K_TARGET = 10
WS_BETA = 0.15

# Monte Carlo setup
GRAPH_SEEDS = list(range(20))      # 20 independent graph realizations
N_RUNS_PER_GRAPH = 20              # 20 shock simulations per graph

cfg_base = SimConfig(
    T=100,
    stop_when_stable=True,
    stability_window=5,
    stability_eps=1e-4,
    min_steps=10,

    shock_fraction=0.03,
    shock_mode="random",
    shock_strength=0.55,
    initial_shock_state="stress",

    r=0.09,
    beta=0.24,
    normalize_incoming=True,

    use_liquidity_spiral=False,
    use_leverage_feedback=False,
    use_herding=False,
)

print("Main cfg_base:")
print(asdict(cfg_base))

df_base = run_all_topologies_over_graphs(
    n=N,
    k_target=K_TARGET,
    ws_beta=WS_BETA,
    cfg=cfg_base,
    graph_seeds=GRAPH_SEEDS,
    n_runs_per_graph=N_RUNS_PER_GRAPH,
    base_seed=2000,
)

df_base["scenario"] = "baseline"

out_path = "results_baseline_multigraph.csv"
df_base.to_csv(out_path, index=False)

print("Saved:", out_path)
print("Rows:", len(df_base))

baseline_summary = df_base.groupby("topology")[[
    "cascade_size",
    "final_default",
    "final_affected",
    "ever_defaulted",
    "peak_default",
    "peak_affected",
    "systemic_by_default",
    "systemic_by_cascade",

    # stopping / timing
    "stop_time",
    "stopped_early",
    "max_T",
    "time_to_90pct_peak_affected",
    "active_cascade_duration_affected",
    "stabilization_time_affected",

    # cumulative burden
    "area_affected",
    "area_default"
]].mean().round(4)

display(baseline_summary)

baseline_summary.to_csv("summary_baseline_multigraph.csv")

# [CELL 8A] Quick calibration grid for baseline parameters

# calib_rows = []
# N = 300
# K_TARGET = 10
# WS_BETA = 0.15

# beta_values = [0.12, 0.15, 0.18, 0.21, 0.24]
# r_values = [0.09, 0.12, 0.15]
# shock_values = [0.45, 0.50, 0.55, 0.60]

# CALIB_GRAPH_SEEDS = list(range(5))
# CALIB_RUNS_PER_GRAPH = 5

# for beta in beta_values:
#     for r in r_values:
#         for shock_strength in shock_values:
#             cfg_test = SimConfig(
#                 T=100,
#                 stop_when_stable=True,
#                 stability_window=5,
#                 stability_eps=1e-4,
#                 min_steps=10,

#                 shock_fraction=0.03,
#                 shock_mode="random",
#                 shock_strength=shock_strength,
#                 initial_shock_state="stress",
# -
#                 r=r,
#                 beta=beta,
#                 normalize_incoming=True,

#                 use_liquidity_spiral=False,
#                 use_leverage_feedback=False,
#                 use_herding=False,
#             )

#             df_test = run_all_topologies_over_graphs(
#                 n=N,
#                 k_target=K_TARGET,
#                 ws_beta=WS_BETA,
#                 cfg=cfg_test,
#                 graph_seeds=CALIB_GRAPH_SEEDS,
#                 n_runs_per_graph=CALIB_RUNS_PER_GRAPH,
#                 base_seed=9000,
#             )

#             calib_rows.append({
#                 "beta": beta,
#                 "r": r,
#                 "shock_strength": shock_strength,
#                 "mean_cascade_size": df_test["cascade_size"].mean(),
#                 "mean_final_default": df_test["final_default"].mean(),
#                 "mean_systemic_by_default": df_test["systemic_by_default"].mean(),
#                 "mean_systemic_by_cascade": df_test["systemic_by_cascade"].mean(),
#             })

# df_calib = pd.DataFrame(calib_rows)

# display(
#     df_calib.sort_values(
#         ["mean_systemic_by_default", "mean_cascade_size"]
#     ).round(4)
# )

# [CELL 9] Scenario runs: baseline / liquidity / leverage / herding

# We use the same network setup and Monte Carlo structure as in CELL 8:
# N = 300, K_TARGET = 10, WS_BETA = 0.15
# GRAPH_SEEDS and N_RUNS_PER_GRAPH should already be defined in CELL 8.

def make_scenario_config(base_cfg: SimConfig, scenario: str, shock_mode: str = "random") -> SimConfig:
    """
    Creates scenario-specific configs from a common baseline.
    Scenarios:
    - baseline: no additional amplification
    - liquidity: stronger transmission, weaker recovery during crisis window
    - leverage: stressed agents transmit amplified stress
    - herding: stress increases when many neighbors are affected
    """
    cfg_dict = asdict(base_cfg)

    # Reset all scenario toggles
    cfg_dict.update({
        "shock_mode": shock_mode,
        "use_liquidity_spiral": False,
        "use_leverage_feedback": False,
        "use_herding": False,
    })

    if scenario == "baseline":
        pass

    elif scenario == "liquidity":
        cfg_dict.update({
            "use_liquidity_spiral": True,
            "liquidity_t_start": 5,
            "liquidity_t_end": 18,
            "liquidity_beta_mult": 1.25,
            "liquidity_r_mult": 0.85,
        })

    elif scenario == "leverage":
        cfg_dict.update({
            "use_leverage_feedback": True,
            "tau_mean": 0.65,
            "tau_std": 0.10,
            "leverage_lambda": 0.50,
        })

    elif scenario == "herding":
        cfg_dict.update({
            "use_herding": True,
            "phi_mean": 0.35,
            "phi_std": 0.08,
            "herding_h": 0.25,
        })

    else:
        raise ValueError(f"Unknown scenario={scenario}")

    return SimConfig(**cfg_dict)


SCENARIOS = ["baseline", "liquidity", "leverage", "herding"]

scenario_dfs = []

for scenario in SCENARIOS:
    cfg_scenario = make_scenario_config(
        base_cfg=cfg_base,
        scenario=scenario,
        shock_mode="random"
    )

    df_s = run_all_topologies_over_graphs(
        n=N,
        k_target=K_TARGET,
        ws_beta=WS_BETA,
        cfg=cfg_scenario,
        graph_seeds=GRAPH_SEEDS,
        n_runs_per_graph=N_RUNS_PER_GRAPH,
        base_seed=10000 + 1000 * SCENARIOS.index(scenario),
    )

    df_s["scenario"] = scenario
    df_s["shock_mode_experiment"] = "random"

    scenario_dfs.append(df_s)

df_all = pd.concat(scenario_dfs, ignore_index=True)

out_path = "results_all_scenarios_multigraph.csv"
df_all.to_csv(out_path, index=False)

print("Saved:", out_path)
print("Rows:", len(df_all))

df_all.groupby(["scenario", "topology"])[[
    "cascade_size",
    "final_default",
    "final_affected",
    "ever_defaulted",
    "peak_default",
    "peak_affected",
    "systemic_by_default",
    "systemic_by_cascade",
    "time_to_90pct_peak_affected",
    "active_cascade_duration_affected",
    "stabilization_time_affected",
    "area_affected",
    "area_default"
]].mean().round(4)

# [CELL 10] Targeted vs random shock comparison

# This block tests whether topology effects differ when the initial shock
# hits random nodes versus structurally central/high-degree nodes.

SHOCK_MODES = ["random", "targeted"]

rt_dfs = []

for shock_mode in SHOCK_MODES:
    cfg_rt = make_scenario_config(
        base_cfg=cfg_base,
        scenario="baseline",
        shock_mode=shock_mode
    )

    df_rt_part = run_all_topologies_over_graphs(
        n=N,
        k_target=K_TARGET,
        ws_beta=WS_BETA,
        cfg=cfg_rt,
        graph_seeds=GRAPH_SEEDS,
        n_runs_per_graph=N_RUNS_PER_GRAPH,
        base_seed=30000 + 10000 * SHOCK_MODES.index(shock_mode),
    )

    df_rt_part["scenario"] = "baseline"
    df_rt_part["shock_mode_experiment"] = shock_mode

    rt_dfs.append(df_rt_part)

df_rt = pd.concat(rt_dfs, ignore_index=True)

out_path = "results_random_vs_targeted_multigraph.csv"
df_rt.to_csv(out_path, index=False)

print("Saved:", out_path)
print("Rows:", len(df_rt))

df_rt.groupby(["shock_mode_experiment", "topology"])[[
    "cascade_size",
    "final_default",
    "final_affected",
    "ever_defaulted",
    "peak_default",
    "peak_affected",
    "systemic_by_default",
    "systemic_by_cascade",
    "time_to_90pct_peak_affected",
    "active_cascade_duration_affected",
    "stabilization_time_affected",
    "area_affected",
    "area_default"
]].mean().round(4)

# [CELL 11] Summary tables + quick plots


def summarize_results(df: pd.DataFrame, group_cols: list) -> pd.DataFrame:
    g = df.groupby(group_cols)

    out = g.agg(
        runs=("cascade_size", "size"),

        cascade_mean=("cascade_size", "mean"),
        cascade_median=("cascade_size", "median"),
        cascade_std=("cascade_size", "std"),

        final_default_mean=("final_default", "mean"),
        final_default_median=("final_default", "median"),
        final_default_std=("final_default", "std"),

        final_affected_mean=("final_affected", "mean"),
        ever_defaulted_mean=("ever_defaulted", "mean"),

        peak_default_mean=("peak_default", "mean"),
        peak_affected_mean=("peak_affected", "mean"),

        p_systemic_default=("systemic_by_default", "mean"),
        p_systemic_cascade=("systemic_by_cascade", "mean"),

        time_to_90pct_peak_affected_mean=("time_to_90pct_peak_affected", "mean"),
        active_cascade_duration_affected_mean=("active_cascade_duration_affected", "mean"),
        stabilization_time_affected_mean=("stabilization_time_affected", "mean"),

        area_affected_mean=("area_affected", "mean"),
        area_default_mean=("area_default", "mean"),

        p95_cascade=("cascade_size", lambda x: float(np.percentile(x, 95))),
        p95_default=("final_default", lambda x: float(np.percentile(x, 95))),
    ).reset_index()

    return out


summary_all = summarize_results(df_all, ["scenario", "topology"])
summary_rt = summarize_results(df_rt, ["shock_mode_experiment", "topology"])

display(summary_all.sort_values(["scenario", "topology"]))
display(summary_rt.sort_values(["shock_mode_experiment", "topology"]))

summary_all.to_csv("summary_all_scenarios.csv", index=False)
summary_rt.to_csv("summary_random_vs_targeted.csv", index=False)


def plot_metric_scatter_means(
    df: pd.DataFrame,
    metric: str,
    group_col: str,
    title: str
):
    groups = df[group_col].unique().tolist()
    tops = df["topology"].unique().tolist()

    plt.figure(figsize=(11, 5))

    x_positions = []
    labels = []
    x = 0

    for g in groups:
        for topo in tops:
            sub = df[(df[group_col] == g) & (df["topology"] == topo)]
            ys = sub[metric].values

            if len(ys) == 0:
                continue

            jitter = (np.random.rand(len(ys)) - 0.5) * 0.18
            xs = np.full(len(ys), x) + jitter

            plt.scatter(xs, ys, s=8, alpha=0.25)
            plt.scatter([x], [ys.mean()], s=80, marker="x")

            labels.append(f"{g}\n{topo}")
            x_positions.append(x)

            x += 1

        x += 0.7

    plt.xticks(x_positions, labels, rotation=0)
    plt.ylabel(metric)
    plt.title(title)
    plt.grid(True, alpha=0.25)
    plt.show()


plot_metric_scatter_means(
    df_all,
    metric="cascade_size",
    group_col="scenario",
    title="Cascade size by scenario and topology"
)

plot_metric_scatter_means(
    df_all,
    metric="final_default",
    group_col="scenario",
    title="Final default fraction by scenario and topology"
)

plot_metric_scatter_means(
    df_all,
    metric="systemic_by_cascade",
    group_col="scenario",
    title="Systemic cascade indicator by scenario and topology"
)

plot_metric_scatter_means(
    df_rt,
    metric="cascade_size",
    group_col="shock_mode_experiment",
    title="Cascade size: random vs targeted shock"
)

plot_metric_scatter_means(
    df_rt,
    metric="final_default",
    group_col="shock_mode_experiment",
    title="Final default: random vs targeted shock"
)

# [CELL 12] Statistical tests: Kruskal-Wallis + Mann-Whitney U

def holm_correction(p_values: List[float]) -> List[float]:
    """
    Holm-Bonferroni correction for multiple comparisons.
    Returns adjusted p-values in the original order.
    """
    p_values = np.array(p_values, dtype=float)
    m = len(p_values)

    if m == 0:
        return []

    order = np.argsort(p_values)
    adjusted = np.empty(m, dtype=float)

    prev = 0.0

    for rank, idx in enumerate(order):
        adj = (m - rank) * p_values[idx]
        adj = max(adj, prev)
        adjusted[idx] = min(adj, 1.0)
        prev = adjusted[idx]

    return adjusted.tolist()


def run_tests_by_condition(
    df: pd.DataFrame,
    metric: str,
    condition_cols: List[str],
    topology_col: str = "topology"
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    For each condition:
    1. Kruskal-Wallis test across all topologies.
    2. Pairwise Mann-Whitney U tests with Holm correction.

    Intended use in this notebook:
    run this on graph-level aggregated outcomes, not on raw simulation-level rows.
    """
    kw_rows = []
    pair_rows = []

    for condition, sub in df.groupby(condition_cols):
        if not isinstance(condition, tuple):
            condition = (condition,)

        cond_dict = dict(zip(condition_cols, condition))

        labels = []
        groups = []

        for topo, g in sub.groupby(topology_col):
            vals = g[metric].dropna().values

            if len(vals) > 1:
                labels.append(topo)
                groups.append(vals)

        if len(groups) < 2:
            continue

        stat, p = kruskal(*groups)

        kw_rows.append({
            **cond_dict,
            "metric": metric,
            "test": "Kruskal-Wallis",
            "statistic": stat,
            "p_value": p,
            "significant_5pct": p < 0.05,
            "n_groups": len(groups),
        })

        raw_p = []
        temp_rows = []

        for topo_a, topo_b in combinations(labels, 2):
            x = sub[sub[topology_col] == topo_a][metric].dropna().values
            y = sub[sub[topology_col] == topo_b][metric].dropna().values

            if len(x) == 0 or len(y) == 0:
                continue

            u_stat, p_pair = mannwhitneyu(x, y, alternative="two-sided")

            temp_rows.append({
                **cond_dict,
                "metric": metric,
                "topology_1": topo_a,
                "topology_2": topo_b,
                "test": "Mann-Whitney U",
                "statistic": u_stat,
                "p_value_raw": p_pair,
            })

            raw_p.append(p_pair)

        adjusted_p = holm_correction(raw_p)

        for row, p_adj in zip(temp_rows, adjusted_p):
            row["p_value_holm"] = p_adj
            row["significant_5pct"] = p_adj < 0.05
            pair_rows.append(row)

    return pd.DataFrame(kw_rows), pd.DataFrame(pair_rows)

# [CELL 13] Graph-level aggregation for valid statistical tests


metrics_to_test = [
    "cascade_size",
    "final_default",
    "final_affected",
    "ever_defaulted",
    "peak_default",
    "peak_affected",
    "systemic_by_cascade",
    "systemic_by_default",
    "time_to_90pct_peak_affected",
    "active_cascade_duration_affected",
    "stabilization_time_affected",
    "area_affected",
    "area_default"
]

df_all_graph = (
    df_all
    .groupby(["scenario", "topology", "graph_id"], as_index=False)[metrics_to_test]
    .mean()
)

df_rt_graph = (
    df_rt
    .groupby(["shock_mode_experiment", "topology", "graph_id"], as_index=False)[metrics_to_test]
    .mean()
)

print("df_all original:", df_all.shape)
print("df_all graph-level:", df_all_graph.shape)

print("df_rt original:", df_rt.shape)
print("df_rt graph-level:", df_rt_graph.shape)

display(df_all_graph.head())
display(df_rt_graph.head())

# [CELL 14] Kruskal-Wallis + pairwise Mann-Whitney U on graph-level outcomes


graph_test_outputs = {}

for metric in metrics_to_test:
    kw, pair = run_tests_by_condition(
        df=df_all_graph,
        metric=metric,
        condition_cols=["scenario"]
    )

    graph_test_outputs[f"kw_graph_{metric}"] = kw
    graph_test_outputs[f"pair_graph_{metric}"] = pair

    kw.to_csv(f"GRAPH_tests_kw_by_scenario_{metric}.csv", index=False)
    pair.to_csv(f"GRAPH_tests_pairwise_by_scenario_{metric}.csv", index=False)

    print("\n==============================")
    print("GRAPH-LEVEL Metric:", metric)
    print("Kruskal-Wallis:")
    display(kw)

    print("Pairwise Mann-Whitney U with Holm correction:")
    if len(pair) > 0:
        display(pair.sort_values(["scenario", "p_value_holm"]))
    else:
        display(pair)


rt_graph_test_outputs = {}

for metric in metrics_to_test:
    kw, pair = run_tests_by_condition(
        df=df_rt_graph,
        metric=metric,
        condition_cols=["shock_mode_experiment"]
    )

    rt_graph_test_outputs[f"kw_graph_{metric}"] = kw
    rt_graph_test_outputs[f"pair_graph_{metric}"] = pair

    kw.to_csv(f"GRAPH_tests_kw_random_vs_targeted_{metric}.csv", index=False)
    pair.to_csv(f"GRAPH_tests_pairwise_random_vs_targeted_{metric}.csv", index=False)

    print("\n==============================")
    print("GRAPH-LEVEL Random vs targeted metric:", metric)
    print("Kruskal-Wallis:")
    display(kw)

    print("Pairwise Mann-Whitney U with Holm correction:")
    if len(pair) > 0:
        display(pair.sort_values(["shock_mode_experiment", "p_value_holm"]))
    else:
        display(pair)

# [CELL 15] Effect sizes: Cliff's delta for pairwise topology differences

from itertools import combinations

def cliffs_delta(x, y):
    """
    Cliff's delta:
    P(x > y) - P(x < y).
    Values close to 0 mean weak difference.
    Values close to +/-1 mean strong difference.
    """
    x = np.asarray(x)
    y = np.asarray(y)

    n_x = len(x)
    n_y = len(y)

    if n_x == 0 or n_y == 0:
        return np.nan

    greater = 0
    less = 0

    for xi in x:
        greater += np.sum(xi > y)
        less += np.sum(xi < y)

    return (greater - less) / (n_x * n_y)


def cliffs_delta_label(delta):
    """
    Common rough interpretation thresholds.
    """
    if pd.isna(delta):
        return "NA"

    ad = abs(delta)

    if ad < 0.147:
        return "negligible"
    elif ad < 0.33:
        return "small"
    elif ad < 0.474:
        return "medium"
    else:
        return "large"


def pairwise_effect_sizes_by_condition(
    df: pd.DataFrame,
    metric: str,
    condition_cols: list,
    topology_col: str = "topology"
) -> pd.DataFrame:
    rows = []

    for condition, sub in df.groupby(condition_cols):
        if not isinstance(condition, tuple):
            condition = (condition,)

        cond_dict = dict(zip(condition_cols, condition))

        topologies = sorted(sub[topology_col].dropna().unique())

        for topo_a, topo_b in combinations(topologies, 2):
            x = sub[sub[topology_col] == topo_a][metric].dropna().values
            y = sub[sub[topology_col] == topo_b][metric].dropna().values

            delta = cliffs_delta(x, y)

            rows.append({
                **cond_dict,
                "metric": metric,
                "topology_1": topo_a,
                "topology_2": topo_b,
                "cliffs_delta": delta,
                "effect_size_label": cliffs_delta_label(delta),
                "mean_1": float(np.mean(x)) if len(x) > 0 else np.nan,
                "mean_2": float(np.mean(y)) if len(y) > 0 else np.nan,
                "median_1": float(np.median(x)) if len(x) > 0 else np.nan,
                "median_2": float(np.median(y)) if len(y) > 0 else np.nan,
                "n_1": len(x),
                "n_2": len(y),
            })

    return pd.DataFrame(rows)


effect_outputs = {}

for metric in ["cascade_size", "final_default", "peak_affected", "systemic_by_cascade"]:
    eff = pairwise_effect_sizes_by_condition(
        df=df_all_graph,
        metric=metric,
        condition_cols=["scenario"]
    )

    effect_outputs[metric] = eff
    eff.to_csv(f"GRAPH_effect_sizes_by_scenario_{metric}.csv", index=False)

    print("\n==============================")
    print("Effect sizes for:", metric)
    display(eff.sort_values(["scenario", "effect_size_label", "topology_1", "topology_2"]))


rt_effect_outputs = {}

for metric in ["cascade_size", "final_default", "peak_affected", "systemic_by_cascade"]:
    eff = pairwise_effect_sizes_by_condition(
        df=df_rt_graph,
        metric=metric,
        condition_cols=["shock_mode_experiment"]
    )

    rt_effect_outputs[metric] = eff
    eff.to_csv(f"GRAPH_effect_sizes_random_vs_targeted_{metric}.csv", index=False)

    print("Random vs targeted effect sizes for:", metric)
    display(eff.sort_values(["shock_mode_experiment", "effect_size_label", "topology_1", "topology_2"]))

# [CELL 16] Bootstrap confidence intervals for graph-level outcomes


def bootstrap_ci(samples, stat_fn=np.mean, B=2000, alpha=0.05, seed=123):
    rng = np.random.default_rng(seed)
    samples = np.asarray(samples)

    n = len(samples)

    if n == 0:
        return np.nan, np.nan

    stats = np.empty(B)

    for b in range(B):
        resample = rng.choice(samples, size=n, replace=True)
        stats[b] = stat_fn(resample)

    lo = float(np.quantile(stats, alpha / 2))
    hi = float(np.quantile(stats, 1 - alpha / 2))

    return lo, hi


def bootstrap_summary_table(
    df: pd.DataFrame,
    metric: str,
    group_cols: list,
    B: int = 2000
) -> pd.DataFrame:
    rows = []

    for key, sub in df.groupby(group_cols):
        if not isinstance(key, tuple):
            key = (key,)

        group_dict = dict(zip(group_cols, key))
        vals = sub[metric].dropna().values

        mean_val = float(np.mean(vals)) if len(vals) > 0 else np.nan
        median_val = float(np.median(vals)) if len(vals) > 0 else np.nan
        std_val = float(np.std(vals, ddof=1)) if len(vals) > 1 else np.nan

        ci_lo, ci_hi = bootstrap_ci(vals, np.mean, B=B, seed=123)

        rows.append({
            **group_dict,
            "metric": metric,
            "n": len(vals),
            "mean": mean_val,
            "median": median_val,
            "std": std_val,
            "ci95_low": ci_lo,
            "ci95_high": ci_hi,
        })

    return pd.DataFrame(rows)


ci_tables = []

for metric in ["cascade_size", "final_default", "peak_affected", "systemic_by_cascade"]:
    ci = bootstrap_summary_table(
        df=df_all_graph,
        metric=metric,
        group_cols=["scenario", "topology"],
        B=2000
    )

    ci_tables.append(ci)
    ci.to_csv(f"GRAPH_bootstrap_ci_by_scenario_{metric}.csv", index=False)

    print("\n==============================")
    print("Bootstrap CI for:", metric)
    display(ci.sort_values(["scenario", "topology"]))

ci_all = pd.concat(ci_tables, ignore_index=True)
ci_all.to_csv("GRAPH_bootstrap_ci_all_metrics.csv", index=False)

# [CELL 17] Chi-square tests for systemic-event probabilities

from scipy.stats import chi2_contingency


def chi_square_systemic_by_condition(
    df: pd.DataFrame,
    binary_metric: str,
    condition_cols: list,
    topology_col: str = "topology"
) -> pd.DataFrame:
    rows = []

    for condition, sub in df.groupby(condition_cols):
        if not isinstance(condition, tuple):
            condition = (condition,)

        cond_dict = dict(zip(condition_cols, condition))

        contingency = pd.crosstab(sub[topology_col], sub[binary_metric])

        for col in [0, 1]:
            if col not in contingency.columns:
                contingency[col] = 0

        contingency = contingency[[0, 1]]

        if contingency.shape[0] < 2:
            continue

        try:
            chi2, p, dof, expected = chi2_contingency(contingency.values)
        except ValueError:
            chi2, p, dof = np.nan, np.nan, np.nan

        rows.append({
            **cond_dict,
            "binary_metric": binary_metric,
            "test": "Chi-square independence",
            "chi2_statistic": chi2,
            "p_value": p,
            "dof": dof,
            "significant_5pct": bool(p < 0.05) if not pd.isna(p) else False,
            "contingency_table": contingency.to_dict(),
        })

    return pd.DataFrame(rows)


# Graph-level systemic flags:
# equals 1 if systemic event occurs in at least half of runs on this graph.
df_all_graph_binary = (
    df_all
    .groupby(["scenario", "topology", "graph_id"], as_index=False)
    .agg(
        systemic_by_cascade=("systemic_by_cascade", lambda x: int(np.mean(x) >= 0.5)),
        systemic_by_default=("systemic_by_default", lambda x: int(np.mean(x) >= 0.5)),
    )
)

for binary_metric in ["systemic_by_cascade", "systemic_by_default"]:
    chi = chi_square_systemic_by_condition(
        df=df_all_graph_binary,
        binary_metric=binary_metric,
        condition_cols=["scenario"]
    )

    chi.to_csv(f"GRAPH_BINARY_chi_square_by_scenario_{binary_metric}.csv", index=False)

    print("\n==============================")
    print("Graph-level binary Chi-square tests for:", binary_metric)
    display(chi)

# [CELL 18] Robustness checks: system size and average connectivity

# This robustness block checks two separate dimensions:
# 1. system size: small / medium / large banking systems;
# 2. connectivity: sparse / baseline / dense networks at fixed N=300.

ROBUST_SIZE_GRID = [
    {
        "N_value": 50,
        "K_value": 6,
        "robustness_type": "size",
        "regime_label": "small_system"
    },
    {
        "N_value": 300,
        "K_value": 10,
        "robustness_type": "size",
        "regime_label": "medium_system_baseline"
    },
    {
        "N_value": 800,
        "K_value": 14,
        "robustness_type": "size",
        "regime_label": "large_system"
    },
]

ROBUST_CONNECTIVITY_GRID = [
    {
        "N_value": 300,
        "K_value": 6,
        "robustness_type": "connectivity",
        "regime_label": "sparse_network"
    },
    {
        "N_value": 300,
        "K_value": 10,
        "robustness_type": "connectivity",
        "regime_label": "baseline_network"
    },
    {
        "N_value": 300,
        "K_value": 14,
        "robustness_type": "connectivity",
        "regime_label": "dense_network"
    },
]

ROBUST_GRID = ROBUST_SIZE_GRID + ROBUST_CONNECTIVITY_GRID

ROBUST_SCENARIOS = ["baseline", "leverage"]

GRAPH_SEEDS_ROBUST = list(range(10))   # smaller than main analysis
N_RUNS_ROBUST = 10                     # smaller than main analysis

robust_dfs = []

for grid_item in ROBUST_GRID:
    N_rob = grid_item["N_value"]
    K_rob = grid_item["K_value"]
    robustness_type = grid_item["robustness_type"]
    regime_label = grid_item["regime_label"]

    for scenario in ROBUST_SCENARIOS:

        cfg_rob = make_scenario_config(
            base_cfg=cfg_base,
            scenario=scenario,
            shock_mode="random"
        )

        # A deterministic seed formula for reproducibility.
        # The additional hashes avoid accidental overlap between regimes.
        seed_offset = (
            70000
            + 1000 * N_rob
            + 10 * K_rob
            + 100 * ROBUST_SCENARIOS.index(scenario)
            + 100000 * ROBUST_GRID.index(grid_item)
        )

        df_rob = run_all_topologies_over_graphs(
            n=N_rob,
            k_target=K_rob,
            ws_beta=WS_BETA,
            cfg=cfg_rob,
            graph_seeds=GRAPH_SEEDS_ROBUST,
            n_runs_per_graph=N_RUNS_ROBUST,
            base_seed=seed_offset,
        )

        df_rob["scenario"] = scenario
        df_rob["N_value"] = N_rob
        df_rob["K_value"] = K_rob
        df_rob["robustness_type"] = robustness_type
        df_rob["regime_label"] = regime_label
        df_rob["shock_mode_experiment"] = "random"

        robust_dfs.append(df_rob)

df_robust = pd.concat(robust_dfs, ignore_index=True)

out_path = "results_robustness_size_connectivity.csv"
df_robust.to_csv(out_path, index=False)

print("Saved:", out_path)
print("Rows:", len(df_robust))

robust_summary = (
    df_robust
    .groupby([
        "robustness_type",
        "regime_label",
        "N_value",
        "K_value",
        "scenario",
        "topology"
    ])[[
        "cascade_size",
        "final_default",
        "final_affected",
        "ever_defaulted",
        "peak_default",
        "peak_affected",
        "systemic_by_cascade",
        "systemic_by_default"
    ]]
    .mean()
    .round(4)
    .reset_index()
)

display(robust_summary)

robust_summary.to_csv("summary_robustness_size_connectivity.csv", index=False)

# [CELL X] Time-horizon sensitivity check


T_VALUES = [45, 50, 55, 60]

GRAPH_SEEDS_TCHECK = list(range(8))
N_RUNS_TCHECK = 8

tcheck_dfs = []

for T_val in T_VALUES:
    cfg_t = SimConfig(
        **{
            **asdict(cfg_base),
            "T": T_val
        }
    )

    df_t = run_all_topologies_over_graphs(
        n=N,
        k_target=K_TARGET,
        ws_beta=WS_BETA,
        cfg=cfg_t,
        graph_seeds=GRAPH_SEEDS_TCHECK,
        n_runs_per_graph=N_RUNS_TCHECK,
        base_seed=250000 + 1000 * T_val,
    )

    df_t["scenario"] = "baseline"
    df_t["T_value"] = T_val

    tcheck_dfs.append(df_t)

df_tcheck = pd.concat(tcheck_dfs, ignore_index=True)

tcheck_summary = (
    df_tcheck
    .groupby(["T_value", "topology"])[[
        "cascade_size",
        "final_default",
        "final_affected",
        "systemic_by_default",
        "systemic_by_cascade",
        "time_to_90pct_peak_affected",
        "active_cascade_duration_affected",
        "stabilization_time_affected",
        "area_affected",
        "area_default"
    ]]
    .mean()
    .round(4)
    .reset_index()
)

display(tcheck_summary)

tcheck_summary.to_csv("summary_time_horizon_sensitivity.csv", index=False)

def plot_t_sensitivity(summary, metric):
    plt.figure(figsize=(7, 4))

    for topo in summary["topology"].unique():
        sub = summary[summary["topology"] == topo].sort_values("T_value")
        plt.plot(sub["T_value"], sub[metric], marker="o", label=topo)

    plt.xlabel("T")
    plt.ylabel(metric)
    plt.title(f"Time-horizon sensitivity: {metric}")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()


for metric in [
    "cascade_size",
    "final_default",
    "systemic_by_default",
    "systemic_by_cascade",
    "area_default"
]:
    plot_t_sensitivity(tcheck_summary, metric)

# [CELL 19] Statistical tests for robustness runs


robust_metrics = [
    "cascade_size",
    "final_default",
    "final_affected",
    "ever_defaulted",
    "peak_default",
    "peak_affected",
    "systemic_by_cascade",
    "systemic_by_default"
]

# Important:
# We aggregate outcomes at the graph level before statistical testing.
# This avoids treating repeated simulations on the same graph as fully independent observations.
df_robust_graph = (
    df_robust
    .groupby([
        "robustness_type",
        "regime_label",
        "N_value",
        "K_value",
        "scenario",
        "topology",
        "graph_id"
    ], as_index=False)[robust_metrics]
    .mean()
)

robust_test_outputs = {}

for metric in robust_metrics:
    kw, pair = run_tests_by_condition(
        df=df_robust_graph,
        metric=metric,
        condition_cols=[
            "robustness_type",
            "regime_label",
            "N_value",
            "K_value",
            "scenario"
        ]
    )

    robust_test_outputs[f"kw_robust_{metric}"] = kw
    robust_test_outputs[f"pair_robust_{metric}"] = pair

    kw.to_csv(f"ROBUST_kw_size_connectivity_{metric}.csv", index=False)
    pair.to_csv(f"ROBUST_pairwise_size_connectivity_{metric}.csv", index=False)

    print("\n==============================")
    print("Robustness metric:", metric)
    print("Kruskal-Wallis:")
    display(kw)

    print("Pairwise Mann-Whitney U:")
    if len(pair) > 0:
        display(
            pair.sort_values([
                "robustness_type",
                "regime_label",
                "scenario",
                "p_value_holm"
            ])
        )
    else:
        display(pair)

# [CELL 20] Parameter grid: shock intensity and transmission strength


# This grid is used to study threshold behavior:
# weak shocks should die out, strong shocks may trigger systemic cascades,
# and the intermediate region is where topology matters most.

GRID_SHOCK_STRENGTHS = [0.55, 0.60, 0.65, 0.70, 0.75, 0.80]
GRID_BETAS = [0.24, 0.26, 0.28, 0.30]

GRID_SCENARIOS = ["baseline", "leverage"]

GRAPH_SEEDS_GRID = list(range(10))
N_RUNS_GRID = 10

grid_dfs = []

for scenario in GRID_SCENARIOS:
    for shock_strength in GRID_SHOCK_STRENGTHS:
        for beta_val in GRID_BETAS:

            cfg_grid_base = SimConfig(
                **{
                    **asdict(cfg_base),
                    "shock_strength": float(shock_strength),
                    "beta": float(beta_val)
                }
            )

            cfg_grid = make_scenario_config(
                base_cfg=cfg_grid_base,
                scenario=scenario,
                shock_mode="random"
            )

            seed_offset = (
                150000
                + 10000 * GRID_SCENARIOS.index(scenario)
                + int(1000 * shock_strength)
                + int(100 * beta_val)
            )

            df_grid_part = run_all_topologies_over_graphs(
                n=N,
                k_target=K_TARGET,
                ws_beta=WS_BETA,
                cfg=cfg_grid,
                graph_seeds=GRAPH_SEEDS_GRID,
                n_runs_per_graph=N_RUNS_GRID,
                base_seed=seed_offset,
            )

            df_grid_part["scenario"] = scenario
            df_grid_part["shock_strength_grid"] = float(shock_strength)
            df_grid_part["beta_grid"] = float(beta_val)
            df_grid_part["shock_mode_experiment"] = "random"

            grid_dfs.append(df_grid_part)

df_param_grid = pd.concat(grid_dfs, ignore_index=True)

df_param_grid.to_csv("results_parameter_grid_shock_beta.csv", index=False)

param_grid_summary = (
    df_param_grid
    .groupby(["scenario", "shock_strength_grid", "beta_grid", "topology"])[[
        "cascade_size",
        "final_default",
        "final_affected",
        "ever_defaulted",
        "peak_affected",
        "systemic_by_default",
        "systemic_by_cascade",
        "area_affected",
        "area_default",
        "time_to_90pct_peak_affected",
        "active_cascade_duration_affected",
        "stabilization_time_affected"
    ]]
    .mean()
    .round(4)
    .reset_index()
)

display(param_grid_summary)

param_grid_summary.to_csv("summary_parameter_grid_shock_beta.csv", index=False)

# [CELL 21] Main scenario comparison plots


def plot_grouped_bar_means(df, group_col, metric, title, ylabel=None):
    summary = (
        df.groupby([group_col, "topology"])[metric]
        .mean()
        .reset_index()
    )

    groups = summary[group_col].unique().tolist()
    topologies = ["ER", "WS", "BA", "CMP"]

    x = np.arange(len(groups))
    width = 0.18

    plt.figure(figsize=(10, 5))

    for i, topo in enumerate(topologies):
        vals = []
        for g in groups:
            sub = summary[(summary[group_col] == g) & (summary["topology"] == topo)]
            vals.append(float(sub[metric].iloc[0]) if len(sub) > 0 else np.nan)

        plt.bar(x + (i - 1.5) * width, vals, width=width, label=topo)

    plt.xticks(x, groups)
    plt.ylabel(ylabel if ylabel is not None else metric)
    plt.title(title)
    plt.legend(title="Topology")
    plt.grid(axis="y", alpha=0.3)
    plt.show()


plot_grouped_bar_means(
    df_all,
    group_col="scenario",
    metric="cascade_size",
    title="Mean cascade size by scenario and topology",
    ylabel="Mean cascade size"
)

plot_grouped_bar_means(
    df_all,
    group_col="scenario",
    metric="final_default",
    title="Mean final default fraction by scenario and topology",
    ylabel="Mean final default fraction"
)

plot_grouped_bar_means(
    df_all,
    group_col="scenario",
    metric="area_default",
    title="Cumulative default burden by scenario and topology",
    ylabel="Area under default curve"
)

# [CELL 22] Boxplots on graph-level outcomes


def plot_boxplots_by_scenario(df_graph, metric, title):
    scenarios = ["baseline", "herding", "leverage", "liquidity"]
    topologies = ["ER", "WS", "BA", "CMP"]

    data = []
    labels = []
    positions = []
    pos = 0

    for scenario in scenarios:
        for topo in topologies:
            vals = df_graph[
                (df_graph["scenario"] == scenario) &
                (df_graph["topology"] == topo)
            ][metric].dropna().values

            data.append(vals)
            labels.append(f"{scenario}\n{topo}")
            positions.append(pos)
            pos += 1

        pos += 0.8

    plt.figure(figsize=(13, 5))
    plt.boxplot(data, positions=positions, widths=0.6, showfliers=True)
    plt.xticks(positions, labels, rotation=0)
    plt.ylabel(metric)
    plt.title(title)
    plt.grid(axis="y", alpha=0.3)
    plt.show()


plot_boxplots_by_scenario(
    df_all_graph,
    metric="cascade_size",
    title="Graph-level cascade size distributions by scenario and topology"
)

plot_boxplots_by_scenario(
    df_all_graph,
    metric="final_default",
    title="Graph-level final default distributions by scenario and topology"
)

plot_boxplots_by_scenario(
    df_all_graph,
    metric="area_default",
    title="Graph-level default burden distributions by scenario and topology"
)

# [CELL 23] Random vs targeted shock plots


plot_grouped_bar_means(
    df_rt,
    group_col="shock_mode_experiment",
    metric="cascade_size",
    title="Cascade size under random vs targeted shocks",
    ylabel="Mean cascade size"
)

plot_grouped_bar_means(
    df_rt,
    group_col="shock_mode_experiment",
    metric="final_default",
    title="Final default fraction under random vs targeted shocks",
    ylabel="Mean final default fraction"
)

plot_grouped_bar_means(
    df_rt,
    group_col="shock_mode_experiment",
    metric="systemic_by_default",
    title="Probability of systemic default under random vs targeted shocks",
    ylabel="Systemic default probability"
)

# [CELL 24] Bootstrap confidence interval plots


def plot_ci_by_scenario(ci_df, metric, title):
    sub = ci_df[ci_df["metric"] == metric].copy()

    scenarios = ["baseline", "herding", "leverage", "liquidity"]
    topologies = ["ER", "WS", "BA", "CMP"]

    plt.figure(figsize=(12, 5))

    x_positions = []
    labels = []
    x = 0

    for scenario in scenarios:
        for topo in topologies:
            row = sub[
                (sub["scenario"] == scenario) &
                (sub["topology"] == topo)
            ]

            if len(row) == 0:
                continue

            mean = float(row["mean"].iloc[0])
            lo = float(row["ci95_low"].iloc[0])
            hi = float(row["ci95_high"].iloc[0])

            plt.errorbar(
                x,
                mean,
                yerr=[[mean - lo], [hi - mean]],
                fmt="o",
                capsize=4
            )

            x_positions.append(x)
            labels.append(f"{scenario}\n{topo}")
            x += 1

        x += 0.7

    plt.xticks(x_positions, labels, rotation=0)
    plt.ylabel(metric)
    plt.title(title)
    plt.grid(axis="y", alpha=0.3)
    plt.show()


plot_ci_by_scenario(
    ci_all,
    metric="cascade_size",
    title="Bootstrap 95% CI for cascade size"
)

plot_ci_by_scenario(
    ci_all,
    metric="final_default",
    title="Bootstrap 95% CI for final default fraction"
)

plot_ci_by_scenario(
    ci_all,
    metric="systemic_by_cascade",
    title="Bootstrap 95% CI for systemic cascade probability"
)

# [CELL 21] Report-quality plotting utilities


import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

FIG_DIR = "report_figures"
os.makedirs(FIG_DIR, exist_ok=True)

# Fixed order for consistency across all figures
TOPOLOGY_ORDER = ["ER", "WS", "BA", "CMP"]
SCENARIO_ORDER = ["baseline", "herding", "leverage", "liquidity"]
SHOCK_ORDER = ["random", "targeted"]

# Consistent colors for topologies
TOPOLOGY_COLORS = {
    "ER": "#4C78A8",
    "WS": "#F58518",
    "BA": "#54A24B",
    "CMP": "#E45756",
}

def _mean_ci95(x):
    """
    Mean and approximate 95% CI using normal approximation.
    This is fine for graph-level means as a visual summary.
    """
    x = pd.Series(x).dropna().astype(float)
    n = len(x)
    mean = x.mean()
    std = x.std(ddof=1) if n > 1 else 0.0
    se = std / np.sqrt(n) if n > 1 else 0.0
    ci = 1.96 * se
    return mean, ci, n


def save_current_fig(filename):
    path = os.path.join(FIG_DIR, filename)
    plt.tight_layout()
    plt.savefig(path, dpi=300, bbox_inches="tight")
    plt.show()
    print("Saved:", path)

# [CELL 22] Main scenario comparison: mean ± 95% CI


def plot_grouped_bar_ci(
    df_graph,
    group_col,
    group_order,
    metric,
    title,
    ylabel,
    filename,
    topology_order=TOPOLOGY_ORDER,
):
    rows = []

    for group in group_order:
        for topo in topology_order:
            vals = df_graph[
                (df_graph[group_col] == group) &
                (df_graph["topology"] == topo)
            ][metric]

            mean, ci, n = _mean_ci95(vals)

            rows.append({
                group_col: group,
                "topology": topo,
                "mean": mean,
                "ci95": ci,
                "n": n,
            })

    summary = pd.DataFrame(rows)

    x = np.arange(len(group_order))
    width = 0.18

    plt.figure(figsize=(9.5, 5.2))

    for i, topo in enumerate(topology_order):
        sub = summary[summary["topology"] == topo]
        means = sub["mean"].values
        cis = sub["ci95"].values

        plt.bar(
            x + (i - 1.5) * width,
            means,
            width=width,
            yerr=cis,
            capsize=3,
            label=topo,
            color=TOPOLOGY_COLORS[topo],
            alpha=0.9,
            edgecolor="black",
            linewidth=0.4,
        )

    plt.xticks(x, group_order)
    plt.ylabel(ylabel)
    plt.title(title)
    plt.legend(title="Topology", frameon=True)
    plt.grid(axis="y", alpha=0.25)

    save_current_fig(filename)


plot_grouped_bar_ci(
    df_graph=df_all_graph,
    group_col="scenario",
    group_order=SCENARIO_ORDER,
    metric="cascade_size",
    title="Mean cascade size by scenario and topology",
    ylabel="Cascade size",
    filename="fig_01_scenario_cascade_size_ci.png",
)

plot_grouped_bar_ci(
    df_graph=df_all_graph,
    group_col="scenario",
    group_order=SCENARIO_ORDER,
    metric="final_default",
    title="Mean final default fraction by scenario and topology",
    ylabel="Final default fraction",
    filename="fig_02_scenario_final_default_ci.png",
)

plot_grouped_bar_ci(
    df_graph=df_all_graph,
    group_col="scenario",
    group_order=SCENARIO_ORDER,
    metric="area_default",
    title="Cumulative default burden by scenario and topology",
    ylabel="Area under default curve",
    filename="fig_03_scenario_area_default_ci.png",
)

# [CELL 23] Graph-level boxplots by scenario and topology

def plot_graph_level_boxplots(
    df_graph,
    metric,
    title,
    ylabel,
    filename,
    scenario_order=SCENARIO_ORDER,
    topology_order=TOPOLOGY_ORDER,
):
    fig, axes = plt.subplots(
        1,
        len(scenario_order),
        figsize=(14, 4.5),
        sharey=True
    )

    if len(scenario_order) == 1:
        axes = [axes]

    for ax, scenario in zip(axes, scenario_order):
        data = []
        labels = []

        for topo in topology_order:
            vals = df_graph[
                (df_graph["scenario"] == scenario) &
                (df_graph["topology"] == topo)
            ][metric].dropna().values

            data.append(vals)
            labels.append(topo)

        bp = ax.boxplot(
            data,
            labels=labels,
            patch_artist=True,
            showfliers=True,
            widths=0.55
        )

        for patch, topo in zip(bp["boxes"], topology_order):
            patch.set_facecolor(TOPOLOGY_COLORS[topo])
            patch.set_alpha(0.55)

        ax.set_title(scenario)
        ax.grid(axis="y", alpha=0.25)

    axes[0].set_ylabel(ylabel)
    fig.suptitle(title, y=1.03)

    save_current_fig(filename)


plot_graph_level_boxplots(
    df_graph=df_all_graph,
    metric="final_default",
    title="Graph-level final default distributions",
    ylabel="Final default fraction",
    filename="fig_04_boxplot_final_default.png",
)

plot_graph_level_boxplots(
    df_graph=df_all_graph,
    metric="cascade_size",
    title="Graph-level cascade size distributions",
    ylabel="Cascade size",
    filename="fig_05_boxplot_cascade_size.png",
)

plot_graph_level_boxplots(
    df_graph=df_all_graph,
    metric="area_default",
    title="Graph-level default burden distributions",
    ylabel="Area under default curve",
    filename="fig_06_boxplot_area_default.png",
)

# [CELL 24] Random vs targeted shock: report plots

plot_grouped_bar_ci(
    df_graph=df_rt_graph,
    group_col="shock_mode_experiment",
    group_order=SHOCK_ORDER,
    metric="cascade_size",
    title="Cascade size under random and targeted shocks",
    ylabel="Cascade size",
    filename="fig_07_random_vs_targeted_cascade_size_ci.png",
)

plot_grouped_bar_ci(
    df_graph=df_rt_graph,
    group_col="shock_mode_experiment",
    group_order=SHOCK_ORDER,
    metric="final_default",
    title="Final default fraction under random and targeted shocks",
    ylabel="Final default fraction",
    filename="fig_08_random_vs_targeted_final_default_ci.png",
)

plot_grouped_bar_ci(
    df_graph=df_rt_graph,
    group_col="shock_mode_experiment",
    group_order=SHOCK_ORDER,
    metric="systemic_by_default",
    title="Systemic default probability under random and targeted shocks",
    ylabel="Systemic default probability",
    filename="fig_09_random_vs_targeted_systemic_default_ci.png",
)

# For probability metrics, use full 0-1 scale
plt.figure(figsize=(1, 1))
plt.close()

# [CELL 25] Bootstrap CI plots from ci_all

def plot_bootstrap_ci_points(
    ci_df,
    metric,
    title,
    ylabel,
    filename,
    scenario_order=SCENARIO_ORDER,
    topology_order=TOPOLOGY_ORDER,
):
    sub = ci_df[ci_df["metric"] == metric].copy()

    plt.figure(figsize=(12, 5))

    x_positions = []
    x_labels = []
    x = 0

    for scenario in scenario_order:
        for topo in topology_order:
            row = sub[
                (sub["scenario"] == scenario) &
                (sub["topology"] == topo)
            ]

            if len(row) == 0:
                continue

            mean = float(row["mean"].iloc[0])
            lo = float(row["ci95_low"].iloc[0])
            hi = float(row["ci95_high"].iloc[0])

            plt.errorbar(
                x,
                mean,
                yerr=[[mean - lo], [hi - mean]],
                fmt="o",
                capsize=4,
                color=TOPOLOGY_COLORS[topo],
                markersize=6,
            )

            x_positions.append(x)
            x_labels.append(f"{scenario}\n{topo}")
            x += 1

        x += 0.7

    plt.xticks(x_positions, x_labels, rotation=45, ha="right")
    plt.ylabel(ylabel)
    plt.title(title)
    plt.grid(axis="y", alpha=0.25)

    save_current_fig(filename)


if "ci_all" in globals():
    plot_bootstrap_ci_points(
        ci_df=ci_all,
        metric="final_default",
        title="Bootstrap 95% confidence intervals for final default fraction",
        ylabel="Final default fraction",
        filename="fig_10_bootstrap_ci_final_default.png",
    )

    plot_bootstrap_ci_points(
        ci_df=ci_all,
        metric="cascade_size",
        title="Bootstrap 95% confidence intervals for cascade size",
        ylabel="Cascade size",
        filename="fig_11_bootstrap_ci_cascade_size.png",
    )

    plot_bootstrap_ci_points(
        ci_df=ci_all,
        metric="systemic_by_cascade",
        title="Bootstrap 95% confidence intervals for systemic cascade probability",
        ylabel="Systemic cascade probability",
        filename="fig_12_bootstrap_ci_systemic_cascade.png",
    )
else:
    print("ci_all is not defined. Run bootstrap CI cell first.")

# [CELL 25] Parameter-grid heatmaps

def plot_grid_heatmap(df, scenario, topology, metric):
    sub = df[
        (df["scenario"] == scenario) &
        (df["topology"] == topology)
    ]

    pivot = sub.pivot_table(
        index="shock_strength_grid",
        columns="beta_grid",
        values=metric,
        aggfunc="mean"
    )

    plt.figure(figsize=(6, 4))
    plt.imshow(pivot.values, aspect="auto", origin="lower")

    plt.xticks(
        ticks=np.arange(len(pivot.columns)),
        labels=[str(c) for c in pivot.columns]
    )
    plt.yticks(
        ticks=np.arange(len(pivot.index)),
        labels=[str(i) for i in pivot.index]
    )

    plt.xlabel("Transmission strength beta")
    plt.ylabel("Shock strength")
    plt.title(f"{metric}: {scenario}, {topology}")
    plt.colorbar(label=metric)
    plt.show()


for scenario in ["baseline", "leverage"]:
    for topology in ["ER", "WS", "BA", "CMP"]:
        plot_grid_heatmap(
            df_param_grid,
            scenario=scenario,
            topology=topology,
            metric="cascade_size"
        )

for scenario in ["baseline", "leverage"]:
    for topology in ["ER", "WS", "BA", "CMP"]:
        plot_grid_heatmap(
            df_param_grid,
            scenario=scenario,
            topology=topology,
            metric="final_default"
        )

# [CELL 26] Robustness plots: connectivity and size regimes

def plot_robustness_grouped_bars(
    robust_summary,
    robustness_type,
    scenario,
    metric,
    title,
    ylabel,
    filename,
    topology_order=TOPOLOGY_ORDER,
):
    sub = robust_summary[
        (robust_summary["robustness_type"] == robustness_type) &
        (robust_summary["scenario"] == scenario)
    ].copy()

    if robustness_type == "connectivity":
        regime_order = ["sparse_network", "baseline_network", "dense_network"]
    elif robustness_type == "size":
        regime_order = ["small_system", "medium_system_baseline", "large_system"]
    else:
        regime_order = sub["regime_label"].unique().tolist()

    x = np.arange(len(regime_order))
    width = 0.18

    plt.figure(figsize=(10, 5))

    for i, topo in enumerate(topology_order):
        vals = []

        for regime in regime_order:
            row = sub[
                (sub["regime_label"] == regime) &
                (sub["topology"] == topo)
            ]

            vals.append(float(row[metric].iloc[0]) if len(row) > 0 else np.nan)

        plt.bar(
            x + (i - 1.5) * width,
            vals,
            width=width,
            label=topo,
            color=TOPOLOGY_COLORS[topo],
            alpha=0.9,
            edgecolor="black",
            linewidth=0.4,
        )

    pretty_labels = [
        r.replace("_", " ")
        .replace("medium system baseline", "medium system")
        .replace("baseline network", "baseline")
        for r in regime_order
    ]

    plt.xticks(x, pretty_labels, rotation=15, ha="right")
    plt.ylabel(ylabel)
    plt.title(title)
    plt.legend(title="Topology")
    plt.grid(axis="y", alpha=0.25)

    save_current_fig(filename)


if "robust_summary" in globals():
    plot_robustness_grouped_bars(
        robust_summary=robust_summary,
        robustness_type="connectivity",
        scenario="baseline",
        metric="final_default",
        title="Connectivity robustness: baseline final default",
        ylabel="Final default fraction",
        filename="fig_13_connectivity_baseline_final_default.png",
    )

    plot_robustness_grouped_bars(
        robust_summary=robust_summary,
        robustness_type="connectivity",
        scenario="leverage",
        metric="final_default",
        title="Connectivity robustness: leverage final default",
        ylabel="Final default fraction",
        filename="fig_14_connectivity_leverage_final_default.png",
    )

    plot_robustness_grouped_bars(
        robust_summary=robust_summary,
        robustness_type="size",
        scenario="baseline",
        metric="final_default",
        title="Size-regime robustness: baseline final default",
        ylabel="Final default fraction",
        filename="fig_15_size_baseline_final_default.png",
    )

    plot_robustness_grouped_bars(
        robust_summary=robust_summary,
        robustness_type="size",
        scenario="leverage",
        metric="final_default",
        title="Size-regime robustness: leverage final default",
        ylabel="Final default fraction",
        filename="fig_16_size_leverage_final_default.png",
    )
else:
    print("robust_summary is not defined. Run robustness cell first.")